# 🩺 Sprint 1 - Prétraitement des données
### Projet : Prédiction du risque de diabète - BRFSS 2015
---
**Formation** : FISE A4 Data & IA - CESI Bordeaux  
**Dataset** : `diabetes_012_health_indicators_BRFSS2015.csv`  
**Livrable** : Sprint 1 : Préparation des données

## Sommaire

1. Contexte
2. Objectif
3. Problématique
4. Contraintes
5. Le dataset et ses variables
6. Analyse éthique des variables à retirer de l'étude
7. Imports et configuration
8. Étape 1 : Chargement et compréhension initiale
9. Étape 2 : Séparation cible et variables explicatives
10. Étape 3 : Découpage train / val / test
11. Étape 4 : Typage des variables
12. Étape 5 : Doublons et valeurs manquantes
13. Étape 6 : Analyse exploratoire quantitative
14. Étape 7 : Analyse exploratoire qualitative (EDA visuelle)
15. Étape 8 : Normalisation
16. Étape 9 : Sauvegarde
17. Analyse RGPD & Éthique
18. Conclusion
19. Glossaire

## 1. Contexte

&nbsp;&nbsp;&nbsp;&nbsp;Aux États-Unis, le diabète est l'une des maladies chroniques les plus répandues. En 2018, les CDC (les Centres pour le contrôle et la prévention des maladies) estimaient à 34,2 millions le nombre d'Américains diabétiques, et à 88 millions ceux en état de prédiabète; dont une grande majorité ignorait leur situation.

Cette maladie cause un dérèglement du sucre sanguin, ce qui, sur le long terme, peut engendrer des complications graves : maladies cardiovasculaires, insuffisance rénale, amputations, perte de la vue. Son coût économique est estimé à près de 400 milliards de dollars par an.

Le dataset utilisé provient du *Behavioral Risk Factor Surveillance System (BRFSS)*, une enquête téléphonique annuelle menée par les CDC auprès de plus de 400 000 Américains. Notre version (2015) contient 253 680 réponses et 22 variables relatives aux comportements de santé, antécédents médicaux et conditions socio-économiques des participants.


&nbsp;&nbsp;&nbsp;&nbsp;Le **livrable 1** constitue la partie "prétraitement" du projet. C'est dans ce dernier que le dataset issu de l'étude BRFSS va être analysé, normalisé et transformé pour que par la suite il soit plus facile d'utiliser ses données à des fins d'entraînement de modèles d'IA de Deep Learning et d'analyses statistiques.  
L'échéance de ce livrable est fixée au 15 mai 2026 à 8h.

## 2. Objectif

Construire un modèle de classification binaire capable de prédire si une personne est diabétique à partir de ses indicateurs de santé.

La variable cible `Diabetes_012` est binarisée comme suit :
- **0** → pas de diabète ou prédiabète (classes 0 et 1 regroupées)
- **1** → diabète (classe 2)

La métrique finale à maximiser est la **ROC AUC** (mesure la capacité du modèle à séparer les classes positives des négatives) sur un jeu de test non étiqueté.

## 3. Problématique

> *À partir des indicateurs de santé comportementaux et médicaux recueillis dans le BRFSS 2015, est-il possible de correctement prédire si une personne souffre de diabète ?*

Ce sprint se concentre uniquement sur la préparation des données : nettoyage, exploration, et normalisation. Les modèles seront construits dans les sprints suivants.

## 4. Contraintes

- Les données provenant du BRFSS présentent un fort déséquilibre entre les classes, puisque regrouper "no diabetes" et "prediabetes" en une seule classe rend la classe minoritaire (diabète) bien moins représentée. C'est pourquoi la métrique retenue est la ROC AUC plutôt que l'accuracy, qui masquerait ce problème.
  
- Le dataset étant issu d'une enquête téléphonique déclarative, les réponses dépendent entièrement de ce que les participants ont bien voulu déclarer, ce qui peut introduire des biais qu'on ne peut pas corriger.  
- Les 22 variables du dataset sont de nature mixte, certaines sont binaires, d'autres ordinales ou continues. Chaque type nécessite un traitement différent lors du prétraitement et de la normalisation, ce qui rend le pipeline plus complexe.  
- Avec 253 680 répondants, le volume de données est conséquent. Il faut faire attention à la performance de calcul et la gestion mémoire tout au long du projet.  
- Enfin, le dataset contient des variables sensibles comme la tension artérielle, le cholestérol ou le sex. Une analyse RGPD et éthique est nécessaire pour justifier les choix de conservation ou de suppression de certaines variables pour éviter les discriminations et les mauvaises interprétations.

## 5. Le dataset et ses variables

L'enquête BRFSS nous a permis de construire un tableau de données de 253 680 lignes et 22 colonnes, toutes encodées en numérique.

**Détaillons ici chaque variable pour en comprendre le sens :**

- **Diabetes_012** (cible, 0/1/2) : indique si la personne n'a pas de diabète (0), est prédiabétique (1) ou diabétique (2)
- **HighBP** (binaire, 0/1) : indique si la personne souffre d'hypertension artérielle
- **HighChol** (binaire, 0/1) : indique si la personne a un taux de cholestérol élevé
- **CholCheck** (binaire, 0/1) : indique si la personne a fait un contrôle du cholestérol au cours des 5 dernières années
- **BMI** (valeur numérique) : indice de masse corporelle de la personne
- **Smoker** (binaire, 0/1) : indique si la personne a fumé au moins 100 cigarettes dans sa vie, soit l'équivalent de 5 paquets
- **Stroke** (binaire, 0/1) : indique si la personne a déjà eu un AVC déclaré par un médecin
- **HeartDiseaseorAttack** (binaire, 0/1) : indique si la personne a déjà eu une maladie coronarienne ou un infarctus du myocarde
- **PhysActivity** (binaire, 0/1) : indique si la personne a pratiqué une activité physique dans les 30 derniers jours, hors activité professionnelle
- **Fruits** (binaire, 0/1) : indique si la personne consomme des fruits au moins une fois par jour
- **Veggies** (binaire, 0/1) : indique si la personne consomme des légumes au moins une fois par jour
- **HvyAlcoholConsump** (binaire, 0/1) : indique si la personne a une consommation excessive d'alcool
- **AnyHealthcare** (binaire, 0/1) : indique si la personne dispose d'une couverture santé
- **NoDocbcCost** (binaire, 0/1) : indique si la personne a déjà renoncé à consulter un médecin pour des raisons financières
- **GenHlth** (ordinale) : état de santé général auto-évalué par la personne (1 = excellent, 5 = mauvais)
- **MentHlth** (continue) : nombre de jours de mauvaise santé mentale ressentis sur les 30 derniers jours
- **PhysHlth** (continue) : nombre de jours de mauvaise santé physique ressentis sur les 30 derniers jours
- **DiffWalk** (binaire, 0/1) : indique si la personne a des difficultés à marcher ou monter des escaliers
- **Sex** (binaire, 0/1) : indique le sexe de la personne (0 = femme, 1 = homme)
- **Age** (ordinale) : tranche d'âge de la personne
- **Education** (ordinale) : niveau d'études de la personne
- **Income** (ordinale) : tranche de revenus de la personne

## 6. Analyse éthique des variables à retirer de l'étude

&nbsp;&nbsp;&nbsp;&nbsp;Dans le domaine de la data et de l'intelligence artificielle (IA), il faut constamment questionner l'éthique derrière les données qui vont être utilisées dans des études.   
Que ce soit de l'analyse de données ou de l'entraînement d'IA, il est important d'assurer l'anonymat des individus et de prévenir les dérives d'analyse dues à tout type de discrimination.   
C'est dans cet objectif que nous avons décidé de retirer quelques variables du dataset, que ce soit parce qu'elles n'ont aucune utilité vis-à-vis de l'étude menée ou parce que l'éthique et la protection des données (RGPD) le demandent.  

- La variable **"Sex"** : Médicalement le sexe peut avoir une légère influence sur le diabète de type 2, mais étant donné que nous prédisons à partir de comportements et d'antécédents médicaux et non de caractéristiques biologiques, il n'est pas utile de la garder. De plus, intégrer le sexe comme variable prédictive pourrait amener le modèle à donner des résultats différents selon le genre ce qui constitue une discrimination de genre qu'il faut éviter.
  
- La variable **"Income"** : Le revenu actuel d'une personne n'est pas un indicateur médical du diabète. Se baser dessus pour prédire une maladie pourrait pénaliser les personnes à faibles revenus qui n'ont pas forcément plus de risques biologiques que les autres, mais simplement moins accès aux soins. Cela amènerait le modèle à des conclusions incorrectes et discriminatoires qu'il faut éviter.

  
- La variable **"Education"** : Le niveau d'études n'est pas un facteur clinique lié au diabète, c'est un facteur social. Un médecin ne diagnostique pas le diabète en fonction du diplôme de son patient. Conserver cette variable amènerait le modèle à discriminer selon le niveau d'études, ce qui n'est ni justifié médicalement ni acceptable éthiquement.

## 7. Imports et configuration

In [11]:
# Suppression des avertissements
# On désactive les warnings Python pour garder la sortie console lisible, notamment les DeprecationWarning de sklearn et pandas.
import warnings
warnings.filterwarnings('ignore')

# Imports des bibliothèques
import pandas as pd          # Tableaux (DataFrames), lecture CSV/Excel, agrégations
import numpy as np           # Calcul numérique, tableaux multidimensionnels, algèbre
import matplotlib.pyplot as plt          # Graphiques de base (axes, figures, subplots)
import matplotlib.ticker as mticker      # Formatage des axes (pourcentages, milliers…)
import seaborn as sns                    # Graphiques statistiques haut niveau (sur matplotlib)
from sklearn.model_selection import train_test_split   # Découpage train / test reproductible
from sklearn.preprocessing import StandardScaler       # Normalisation des features (µ=0, σ=1)
import joblib   # Sauvegarde et rechargement des modèles entraînés (.pkl / .joblib)
from pathlib import Path   # Manipulation des chemins de façon cross-platform (Linux/Windows)

# Configuration globale des graphiques
sns.set_theme(style="whitegrid", palette="muted") # Thème seaborn : grille blanche + palette de couleurs atténuées (muted)
# Paramètres matplotlib par défaut pour toutes les figures du projet
plt.rcParams.update({
    "figure.dpi": 120,        # Résolution en points par pouce (rendu net pour les rapports)
    "figure.figsize": (10, 5) # Dimensions par défaut en pouces (largeur x hauteur)
})

# Définition des répertoires de sortie
PROCESSED_DIR = Path("data/processed")   # Données nettoyées / transformées
FIGURES_DIR   = Path("reports/figures")  # Graphiques exportés (.png, .svg…)
REPORT_DIR    = Path("reports/sprint1")  # Rapports du sprint 1
# Création des dossiers s'ils n'existent pas encore (sans lever d'erreur si déjà présents)
for d in [PROCESSED_DIR, FIGURES_DIR, REPORT_DIR]:
    d.mkdir(parents=True, exist_ok=True)

# Constantes globales du projet
RANDOM_STATE = 42   # Graine aléatoire fixe :résultats reproductibles sur tous les splits/modèles

# Vérification de l'initialisation
print("Imports et configuration OK")

Imports et configuration OK

---
## 8. Étape 1 : Chargement et compréhension initiale du dataset

On commence par charger le CSV brut et regarder ce qu'on a : dimensions, types, premières lignes, statistiques descriptives et valeurs manquantes.

In [12]:
# Chargement du CSV brut
CSV_PATH = "../data/diabetes_012_health_indicators_BRFSS2015.csv"
df_raw = pd.read_csv(CSV_PATH)

print(f"Shape : {df_raw.shape[0]:,} lignes x {df_raw.shape[1]} colonnes")
print(f"Mémoire estimée : {df_raw.memory_usage(deep=True).sum() / 1e6:.2f} Mo")
df_raw.head()

Shape : 253,680 lignes x 22 colonnes
Mémoire estimée : 44.65 Mo

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0

In [13]:
# Types de données et valeurs manquantes
info_df = pd.DataFrame({
    "dtype"    : df_raw.dtypes,
    "n_unique" : df_raw.nunique(),
    "n_missing": df_raw.isnull().sum(),
    "pct_miss" : (df_raw.isnull().mean() * 100).round(2)
})
print(info_df.to_string())
print(f"\nTotal valeurs manquantes : {df_raw.isnull().sum().sum()}")

                        dtype  n_unique  n_missing  pct_miss
Diabetes_012          float64         3          0       0.0
HighBP                float64         2          0       0.0
HighChol              float64         2          0       0.0
CholCheck             float64         2          0       0.0
BMI                   float64        84          0       0.0
Smoker                float64         2          0       0.0
Stroke                float64         2          0       0.0
HeartDiseaseorAttack  float64         2          0       0.0
PhysActivity          float64         2          0       0.0
Fruits                float64         2          0       0.0
Veggies               float64         2          0       0.0
HvyAlcoholConsump     float64         2          0       0.0
AnyHealthcare         float64         2          0       0.0
NoDocbcCost           float64         2          0       0.0
GenHlth               float64         5          0       0.0
MentHlth              float64        31          0       0.0
PhysHlth              float64        31          0       0.0
DiffWalk              float64         2          0       0.0
Sex                   float64         2          0       0.0
Age                   float64        13          0       0.0
Education             float64         6          0       0.0
Income                float64         8          0       0.0

Total valeurs manquantes : 0

In [14]:
# Statistiques descriptives
df_raw.describe().T.round(2)

                         count   mean   std   min   25%   50%   75%   max
Diabetes_012          253680.0   0.30  0.70   0.0   0.0   0.0   0.0   2.0
HighBP                253680.0   0.43  0.49   0.0   0.0   0.0   1.0   1.0
HighChol              253680.0   0.42  0.49   0.0   0.0   0.0   1.0   1.0
CholCheck             253680.0   0.96  0.19   0.0   1.0   1.0   1.0   1.0
BMI                   253680.0  28.38  6.61  12.0  24.0  27.0  31.0  98.0
Smoker                253680.0   0.44  0.50   0.0   0.0   0.0   1.0   1.0
Stroke                253680.0   0.04  0.20   0.0   0.0   0.0   0.0   1.0
HeartDiseaseorAttack  253680.0   0.09  0.29   0.0   0.0   0.0   0.0   1.0
PhysActivity          253680.0   0.76  0.43   0.0   1.0   1.0   1.0   1.0
Fruits                253680.0   0.63  0.48   0.0   0.0   1.0   1.0   1.0
Veggies               253680.0   0.81  0.39   0.0   1.0   1.0   1.0   1.0
HvyAlcoholConsump     253680.0   0.06  0.23   0.0   0.0   0.0   0.0   1.0
AnyHealthcare         253680.0   0.95  0.22   0.0   1.0   1.0   1.0   1.0
NoDocbcCost           253680.0   0.08  0.28   0.0   0.0   0.0   0.0   1.0
GenHlth               253680.0   2.51  1.07   1.0   2.0   2.0   3.0   5.0
MentHlth              253680.0   3.18  7.41   0.0   0.0   0.0   2.0  30.0
PhysHlth              253680.0   4.24  8.72   0.0   0.0   0.0   3.0  30.0
DiffWalk              253680.0   0.17  0.37   0.0   0.0   0.0   0.0   1.0
Sex                   253680.0   0.44  0.50   0.0   0.0   0.0   1.0   1.0
Age                   253680.0   8.03  3.05   1.0   6.0   8.0  10.0  13.0
Education             253680.0   5.05  0.99   1.0   4.0   5.0   6.0   6.0
Income                253680.0   6.05  2.07   1.0   5.0   7.0   8.0   8.0

**Observations :**
- Le dataset contient 253 680 lignes et 22 variables, toutes de type `float64`.
  
- Il n'y a aucune valeur manquante, le BRFSS encode les non-réponses par des codes spécifiques déjà filtrés par le CDC.
- La variable cible `Diabetes_012` prend les valeurs 0, 1 (prédiabète) ou 2 (diabète).
- On observe un déséquilibre des classes : la moyenne de Diabetes_012 est de seulement 0.30 et sa médiane est 0.0, ce qui signifie que la majorité des individus du dataset n'ont pas de diabète. Les cas de prédiabète (1) et de diabète (2) sont donc bien moins représentés. Ce déséquilibre est important à prendre en compte car un modèle mal géré pourrait apprendre à toujours prédire "pas de diabète" et avoir l'air performant, sans jamais détecter les vrais cas.

## Suppression des 3 colonnes exclues de l'analyse

In [15]:
# Suppression des colonnes pour raisons éthiques et RGPD
colonnes_a_supprimer = ["Sex", "Income", "Education"]
colonnes_presentes = [c for c in colonnes_a_supprimer if c in df_raw.columns]
if colonnes_presentes:
    df_raw = df_raw.drop(columns=colonnes_presentes)
    print(f"Colonnes supprimées : {colonnes_presentes}")
else:
    print("Colonnes déjà supprimées, aucune action effectuée.")

print(f"Shape final : {df_raw.shape[0]:,} lignes x {df_raw.shape[1]} colonnes")


# Sauvegarde unique du dataset final nettoyé
df_raw.to_csv(PROCESSED_DIR / "df_clean.csv", index=False)
print("Fichier sauvegardé.")

Colonnes supprimées : ['Sex', 'Income', 'Education']
Shape final : 253,680 lignes x 19 colonnes
Fichier sauvegardé.

---
## 9. Étape 2 : Séparation cible / variables explicatives

On isole la variable cible `Diabetes_012` et on la binarise : les classes 0 (pas de diabète) et 1 (prédiabète) sont regroupées sous la valeur 0. La classe 2 (diabète avéré) devient 1.

In [16]:
# Distribution initiale de la cible
print("Distribution Diabetes_012 avant binarisation :")
print(df_raw["Diabetes_012"].value_counts().sort_index())

# Binarisation
df = df_raw.copy()
df["Diabetes_binary"] = (df["Diabetes_012"] == 2).astype(int)
df = df.drop(columns=["Diabetes_012"])

print("\nDistribution après binarisation :")
print(df["Diabetes_binary"].value_counts().sort_index())
print(f"Taux positif : {df['Diabetes_binary'].mean():.3%}")

Distribution Diabetes_012 avant binarisation :
Diabetes_012
0.0    213703
1.0      4631
2.0     35346
Name: count, dtype: int64

Distribution après binarisation :
Diabetes_binary
0    218334
1     35346
Name: count, dtype: int64
Taux positif : 13.933%

In [17]:
# Séparation X / y
TARGET = "Diabetes_binary"
FEATURES = [c for c in df.columns if c != TARGET]

X_full = df[FEATURES]
y_full = df[TARGET]

print(f"Variables explicatives : {len(FEATURES)}")
print(f"Variable cible : {TARGET}")
print(f"Shape X : {X_full.shape}  &&  Shape y : {y_full.shape}")

Variables explicatives : 18
Variable cible : Diabetes_binary
Shape X : (253680, 18)  &&  Shape y : (253680,)

---
## 10. Étape 3 : Découpage train / validation / test

On effectue le découpage **avant** le nettoyage approfondi pour éviter tout data leakage (les statistiques de normalisation ne doivent pas "voir" le test).

Le découpage est **stratifié** sur la variable cible pour conserver le même ratio de positifs dans chaque partition.

- **Train** : 70%  
- **Validation** : 15%  
- **Test** : 15%

In [18]:
# Découpage du dataset en 3 parties : Train / Validation / Test

# Premier split : on sépare 70% pour l'entraînement et 30% temporaire
# Le "temp" contiendra la validation et le test (qu'on séparera ensuite en 2)
X_train_raw, X_temp, y_train_raw, y_temp = train_test_split(
    X_full,              # les features (variables explicatives)
    y_full,              # la cible (0 = pas diabétique, 1 = diabétique)
    test_size=0.30,      # 30% des données vont dans le set temporaire
    stratify=y_full,     # conserve le même ratio de positifs (15%) dans chaque partie
    random_state=RANDOM_STATE  # fixe la graine aléatoire pour reproduire les mêmes résultats
)

# Deuxième split : on coupe le "temp" en deux parties égales (15% / 15%)
# test_size=0.50 signifie 50% du temp pour val et 50% pour test
# comme le temp = 30% du total, on obtient bien 15% val et 15% test
X_val_raw, X_test_raw, y_val, y_test = train_test_split(
    X_temp,              # le set temporaire (30% du dataset)
    y_temp,              # les cibles correspondantes
    test_size=0.50,      # 50% du temp → validation | 50% du temp en test
    stratify=y_temp,     # conserve le même ratio de positifs dans val et test
    random_state=RANDOM_STATE
)

# Vérification : affichage du nombre de lignes et du taux de positifs
# On vérifie que chaque split a bien ~15.27% de positifs (stratification réussie)
for name, X, y in [
    ("Train", X_train_raw, y_train_raw),
    ("Val  ", X_val_raw,   y_val),
    ("Test ", X_test_raw,  y_test)
]:
    print(f"{name} : {len(X):>7,} lignes  &&  taux positif : {y.mean():.3%}")

Train : 177,576 lignes  &&  taux positif : 13.933%
Val   :  38,052 lignes  &&  taux positif : 13.934%
Test  :  38,052 lignes  &&  taux positif : 13.934%

---
## 11. Étape 4 : Typage des variables

On distingue deux catégories de variables :
- **Variables continues et ordinales** : BMI, MentHlth, PhysHlth, GenHlth, Age qui seront standardisées.
- **Variables binaires** (0/1) : les 13 autres seront conservées en l'état.

In [19]:
# Typage explicite
BINARY_COLS = [
    "HighBP", "HighChol", "CholCheck", "Smoker", "Stroke",
    "HeartDiseaseorAttack", "PhysActivity", "Fruits", "Veggies",
    "HvyAlcoholConsump", "AnyHealthcare", "NoDocbcCost", "DiffWalk"
]
NUMERIC_COLS = ["BMI", "MentHlth", "PhysHlth", "GenHlth", "Age"]

# Application sur le dataset complet (avant split)
df[BINARY_COLS] = df[BINARY_COLS].astype("int8")
df[NUMERIC_COLS] = df[NUMERIC_COLS].astype("float32")
df["Diabetes_binary"]  = df["Diabetes_binary"].astype("int8")

print("Variables binaires  :", BINARY_COLS)
print()
print("Variables numériques:", NUMERIC_COLS)
print()
print(df.dtypes)

Variables binaires  : ['HighBP', 'HighChol', 'CholCheck', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies', 'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'DiffWalk']

Variables numériques: ['BMI', 'MentHlth', 'PhysHlth', 'GenHlth', 'Age']

HighBP                     int8
HighChol                   int8
CholCheck                  int8
BMI                     float32
Smoker                     int8
Stroke                     int8
HeartDiseaseorAttack       int8
PhysActivity               int8
Fruits                     int8
Veggies                    int8
HvyAlcoholConsump          int8
AnyHealthcare              int8
NoDocbcCost                int8
GenHlth                 float32
MentHlth                float32
PhysHlth                float32
DiffWalk                   int8
Age                     float32
Diabetes_binary            int8
dtype: object

---
## 12. Étape 5 : Nettoyage des doublons et gestion des valeurs manquantes

### 5.1 Valeurs manquantes

In [23]:
# Valeurs manquantes
n_missing = df.isnull().sum().sum()
print(f"Total valeurs manquantes : {n_missing}")

if n_missing == 0:
    print("Aucun traitement nécessaire. Le BRFSS ne contient pas de NA dans cette version.")
else:
    print(f" {n_missing} valeurs manquantes détectées, application du protocole de nettoyage...")
    
    for col in BINARY_COLS:
        if df[col].isnull().sum() > 0:
            mode = df[col].mode()[0]
            df[col] = df[col].fillna(mode)
            print(f"   {col} : NA remplacés par le mode ({mode})")
    
    for col in NUMERIC_COLS:
        if df[col].isnull().sum() > 0:
            mediane = df[col].median()
            df[col] = df[col].fillna(mediane)
            print(f"   {col} : NA remplacés par la médiane ({mediane})")
    
    print(f"Valeurs manquantes après traitement : {df.isnull().sum().sum()}")

Total valeurs manquantes : 0
Aucun traitement nécessaire. Le BRFSS ne contient pas de NA dans cette version.

### 5.2 Doublons

Un doublon exact correspond à deux répondants ayant exactement le même profil sur les 21 variables. Étant donné le nombre important de variables binaires, de tels doublons sont plausibles statistiquement et on les supprime.

In [24]:
# Doublons
n_before = len(df)
n_dup = df.duplicated().sum()
print(f"Doublons détectés : {n_dup:,}")

df_clean = df.drop_duplicates().reset_index(drop=True)
n_after = len(df_clean)
print(f"Lignes avant : {n_before:,}  →  après : {n_after:,}  (supprimés : {n_before - n_after:,})")

# Distribution de la cible après nettoyage
print("\nDistribution cible après nettoyage :")
print(df_clean["Diabetes_binary"].value_counts().sort_index())
print(f"Taux positif : {df_clean['Diabetes_binary'].mean():.3%}")

Doublons détectés : 72,918
Lignes avant : 253,680  →  après : 180,762  (supprimés : 72,918)

Distribution cible après nettoyage :
Diabetes_binary
0    148125
1     32637
Name: count, dtype: int64
Taux positif : 18.055%

**Note RGPD/Éthique :**  
La suppression des doublons exacts est une mesure de minimisation des données conforme à l'art. 5.1.c du RGPD. Conserver des données en double sans raison va à l'encontre de ce principe.  

Cela évite également de surestimer le poids de certains profils : si un même profil apparaît plusieurs fois, le modèle lui accorderait plus d'importance qu'il ne le mérite, ce qui ne serait pas représentatif de la réalité.

---
## 13. Étape 6 : Analyse exploratoire quantitative

On analyse les distributions, le déséquilibre des classes et les corrélations avec la variable cible.

In [25]:
# Statistiques descriptives sur le jeu nettoyé
df_clean.describe().T.round(2)

                         count   mean   std   min   25%   50%   75%   max
HighBP                180762.0   0.48  0.50   0.0   0.0   0.0   1.0   1.0
HighChol              180762.0   0.46  0.50   0.0   0.0   0.0   1.0   1.0
CholCheck             180762.0   0.95  0.21   0.0   1.0   1.0   1.0   1.0
BMI                   180762.0  29.18  7.26  12.0  24.0  28.0  33.0  98.0
Smoker                180762.0   0.49  0.50   0.0   0.0   0.0   1.0   1.0
Stroke                180762.0   0.06  0.23   0.0   0.0   0.0   0.0   1.0
HeartDiseaseorAttack  180762.0   0.12  0.33   0.0   0.0   0.0   0.0   1.0
PhysActivity          180762.0   0.69  0.46   0.0   0.0   1.0   1.0   1.0
Fruits                180762.0   0.58  0.49   0.0   0.0   1.0   1.0   1.0
Veggies               180762.0   0.77  0.42   0.0   1.0   1.0   1.0   1.0
HvyAlcoholConsump     180762.0   0.07  0.26   0.0   0.0   0.0   0.0   1.0
AnyHealthcare         180762.0   0.93  0.25   0.0   1.0   1.0   1.0   1.0
NoDocbcCost           180762.0   0.12  0.32   0.0   0.0   0.0   0.0   1.0
GenHlth               180762.0   2.75  1.09   1.0   2.0   3.0   3.0   5.0
MentHlth              180762.0   4.39  8.43   0.0   0.0   0.0   4.0  30.0
PhysHlth              180762.0   5.85  9.79   0.0   0.0   0.0   6.0  30.0
DiffWalk              180762.0   0.23  0.42   0.0   0.0   0.0   0.0   1.0
Age                   180762.0   8.05  3.11   1.0   6.0   8.0  10.0  13.0
Diabetes_binary       180762.0   0.18  0.38   0.0   0.0   0.0   0.0   1.0

In [26]:
# Déséquilibre des classes
counts = df_clean["Diabetes_binary"].value_counts().sort_index()
ratios = counts / counts.sum()
imbalance_ratio = counts[0] / counts[1]

print("Effectifs :")
print(f"  Classe 0 (no diabète / prédiabète) : {counts[0]:,}  ({ratios[0]:.2%})")
print(f"  Classe 1 (diabète)                 : {counts[1]:,}  ({ratios[1]:.2%})")
print(f"\nImbalance ratio (majoritaire / minoritaire) : {imbalance_ratio:.2f}")

Effectifs :
  Classe 0 (no diabète / prédiabète) : 148,125  (81.94%)
  Classe 1 (diabète)                 : 32,637  (18.06%)

Imbalance ratio (majoritaire / minoritaire) : 4.54

In [27]:
# Top corrélations avec la cible
corr = df_clean.drop(columns=["Diabetes_binary"]).corrwith(df_clean["Diabetes_binary"])
corr_sorted = corr.abs().sort_values(ascending=False)

print("Top 10 corrélations (valeur absolue) avec Diabetes_binary :")
for feat, val in zip(corr_sorted.index[:10], corr.loc[corr_sorted.index[:10]]):
    bar = "█" * int(abs(val) * 40)
    print(f"  {feat:<25s} {val:+.3f}  {bar}")

Top 10 corrélations (valeur absolue) avec Diabetes_binary :
  GenHlth                   +0.254  ██████████
  HighBP                    +0.250  █████████
  Age                       +0.193  ███████
  BMI                       +0.191  ███████
  HighChol                  +0.191  ███████
  DiffWalk                  +0.186  ███████
  HeartDiseaseorAttack      +0.158  ██████
  PhysHlth                  +0.129  █████
  Stroke                    +0.089  ███
  CholCheck                 +0.089  ███

---
## 14. Étape 7 : Analyse exploratoire qualitative (EDA visuelle)

In [ ]:
# Figure 1 : Déséquilibre des classes
fig, ax = plt.subplots(figsize=(6, 4))
counts_plot = df_clean["Diabetes_binary"].value_counts().sort_index()
bars = ax.bar(["Classe 0\n(no diabète / prédiabète)", "Classe 1\n(diabète)"],
              counts_plot.values,
              color=["#4C9BE8", "#E8654C"], edgecolor="white", linewidth=1.5)
for bar, val in zip(bars, counts_plot.values):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 500,
            f"{val:,}\n({val/counts_plot.sum():.1%})",
            ha="center", va="bottom", fontsize=10, fontweight="bold")
ax.set_title("Déséquilibre des classes — Diabetes_binary", fontsize=13, fontweight="bold")
ax.set_ylabel("Nombre d'observations")
ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f"{int(x):,}"))
plt.tight_layout()
plt.savefig(FIGURES_DIR / "01_class_imbalance.png", dpi=150, bbox_inches="tight")
plt.show()
print("✅ Figure 1 sauvegardée")

In [ ]:
# Figure 2 : Heatmap de corrélation
fig, ax = plt.subplots(figsize=(14, 11))
corr_matrix = df_clean.corr()
mask = np.triu(np.ones_like(corr_matrix, dtype=bool))
sns.heatmap(corr_matrix, mask=mask, annot=True, fmt=".2f", cmap="RdBu_r",
            center=0, linewidths=0.5, ax=ax, annot_kws={"size": 7})
ax.set_title("Matrice de corrélation — Dataset nettoyé", fontsize=13, fontweight="bold")
plt.tight_layout()
plt.savefig(FIGURES_DIR / "02_correlation_heatmap.png", dpi=150, bbox_inches="tight")
plt.show()
print("✅ Figure 2 sauvegardée")

In [ ]:
# Figure 3 : Distributions des variables numériques
fig, axes = plt.subplots(2, 4, figsize=(16, 7))
axes = axes.flatten()
for i, col in enumerate(NUMERIC_COLS):
    axes[i].hist(df_clean[col], bins=30, color="#4C9BE8", edgecolor="white", alpha=0.85)
    axes[i].set_title(col, fontsize=11, fontweight="bold")
    axes[i].set_ylabel("Fréquence")
# Masquer le dernier subplot vide
axes[-1].set_visible(False)
fig.suptitle("Distribution des variables numériques / ordinales", fontsize=13, fontweight="bold")
plt.tight_layout()
plt.savefig(FIGURES_DIR / "03_numeric_distributions.png", dpi=150, bbox_inches="tight")
plt.show()
print("✅ Figure 3 sauvegardée")

In [ ]:
# Figure 4 : Boxplots par classe pour les variables numériques
fig, axes = plt.subplots(2, 4, figsize=(16, 8))
axes = axes.flatten()
palette = {0: "#4C9BE8", 1: "#E8654C"}
for i, col in enumerate(NUMERIC_COLS):
    sns.boxplot(data=df_clean, x="Diabetes_binary", y=col,
                palette=palette, ax=axes[i], width=0.5)
    axes[i].set_title(col, fontsize=11, fontweight="bold")
    axes[i].set_xlabel("Diabetes_binary")
axes[-1].set_visible(False)
fig.suptitle("Distribution par classe — Variables numériques", fontsize=13, fontweight="bold")
plt.tight_layout()
plt.savefig(FIGURES_DIR / "04_boxplots_by_class.png", dpi=150, bbox_inches="tight")
plt.show()
print("✅ Figure 4 sauvegardée")

In [ ]:
# Figure 5 : Prévalence du diabète par variable binaire
fig, axes = plt.subplots(3, 5, figsize=(18, 10))
axes = axes.flatten()
for i, col in enumerate(BINARY_COLS):
    prev = df_clean.groupby(col)["Diabetes_binary"].mean() * 100
    prev.plot(kind="bar", ax=axes[i], color=["#4C9BE8", "#E8654C"],
              edgecolor="white", width=0.6)
    axes[i].set_title(col, fontsize=9, fontweight="bold")
    axes[i].set_ylabel("% diabète")
    axes[i].set_xlabel("")
    axes[i].set_xticklabels(["Non (0)", "Oui (1)"], rotation=0, fontsize=8)
    axes[i].yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f"{x:.0f}%"))
for j in range(len(BINARY_COLS), len(axes)):
    axes[j].set_visible(False)
fig.suptitle("Prévalence du diabète selon les variables binaires", fontsize=13, fontweight="bold")
plt.tight_layout()
plt.savefig(FIGURES_DIR / "05_binary_prevalence.png", dpi=150, bbox_inches="tight")
plt.show()
print("✅ Figure 5 sauvegardée")

In [ ]:
# Figure 6 : Corrélations avec la cible (barh)
fig, ax = plt.subplots(figsize=(9, 7))
corr_target = df_clean.drop(columns=["Diabetes_binary"]).corrwith(df_clean["Diabetes_binary"])
corr_target_sorted = corr_target.sort_values()
colors = ["#E8654C" if v > 0 else "#4C9BE8" for v in corr_target_sorted]
ax.barh(corr_target_sorted.index, corr_target_sorted.values, color=colors, edgecolor="white")
ax.axvline(0, color="black", linewidth=0.8)
ax.set_title("Corrélation de chaque variable avec Diabetes_binary", fontsize=13, fontweight="bold")
ax.set_xlabel("Coefficient de corrélation de Pearson")
plt.tight_layout()
plt.savefig(FIGURES_DIR / "06_correlation_with_target.png", dpi=150, bbox_inches="tight")
plt.show()
print("✅ Figure 6 sauvegardée")

**Lecture des figures :**
- **Fig. 1** : Le dataset est déséquilibré — ~85% de non-diabétiques vs ~15% de diabétiques. C'est un point critique pour le choix du modèle (Sprint 2).
- **Fig. 2** : Peu de corrélations fortes entre variables explicatives — pas de multicolinéarité évidente à supprimer.
- **Fig. 3 & 4** : BMI, GenHlth et Age montrent des distributions clairement différentes entre les deux classes.
- **Fig. 5** : HighBP, HighChol, DiffWalk et HeartDiseaseorAttack sont fortement associés au diabète.
- **Fig. 6** : GenHlth, HighBP, BMI et DiffWalk sont les variables les plus corrélées à la cible.

---
## 15. Étape 8 : Normalisation

On applique un **StandardScaler** (centrage-réduction) uniquement sur les variables continues/ordinales. Les variables binaires restent en l'état.

Le scaler est **ajusté uniquement sur le train** et appliqué ensuite sur val et test — principe fondamental du MLOps pour éviter toute fuite d'information.

In [ ]:
# Re-découpage à partir du dataset nettoyé (df_clean)
X_clean = df_clean.drop(columns=["Diabetes_binary"])
y_clean = df_clean["Diabetes_binary"]

X_train_raw, X_temp, y_train, y_temp = train_test_split(
    X_clean, y_clean, test_size=0.30, stratify=y_clean, random_state=RANDOM_STATE
)
X_val_raw, X_test_raw, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.50, stratify=y_temp, random_state=RANDOM_STATE
)

print("Découpage final (après nettoyage) :")
for name, X, y in [("Train", X_train_raw, y_train),
                   ("Val  ", X_val_raw,   y_val),
                   ("Test ", X_test_raw,  y_test)]:
    print(f"  {name} → {len(X):>7,} lignes  |  taux positif : {y.mean():.3%}")

In [ ]:
# Standardisation
scaler = StandardScaler()

# Fit UNIQUEMENT sur le train
X_train = X_train_raw.copy()
X_val   = X_val_raw.copy()
X_test  = X_test_raw.copy()

X_train[NUMERIC_COLS] = scaler.fit_transform(X_train_raw[NUMERIC_COLS])
X_val[NUMERIC_COLS]   = scaler.transform(X_val_raw[NUMERIC_COLS])
X_test[NUMERIC_COLS]  = scaler.transform(X_test_raw[NUMERIC_COLS])

print(f"Colonnes standardisées : {NUMERIC_COLS}")
print(f"\nMoyennes sur le train après scaling (doivent être ~0) :")
print(X_train[NUMERIC_COLS].mean().round(4).to_string())
print(f"\nÉcarts-types sur le train après scaling (doivent être ~1) :")
print(X_train[NUMERIC_COLS].std().round(4).to_string())

In [ ]:
# Sauvegarde du scaler
scaler_path = PROCESSED_DIR / "scaler.joblib"
joblib.dump(scaler, scaler_path)
print(f"✅ Scaler sauvegardé : {scaler_path}")

---
## 16. Étape 9 : Sauvegarde du jeu de données nettoyé

In [ ]:
# Sauvegarde de tous les datasets
datasets = {
    "diabetes_clean_full.csv" : df_clean,
    "X_train.csv"             : X_train,
    "X_val.csv"               : X_val,
    "X_test.csv"              : X_test,
    "y_train.csv"             : y_train.to_frame(),
    "y_val.csv"               : y_val.to_frame(),
    "y_test.csv"              : y_test.to_frame(),
}

for filename, dataset in datasets.items():
    path = PROCESSED_DIR / filename
    dataset.to_csv(path, index=False)
    print(f"  ✅ {filename:<35s} ({len(dataset):,} lignes)")

print(f"\n📁 Tous les fichiers sont dans : {PROCESSED_DIR}/")

In [ ]:
# Récapitulatif final
print("=" * 55)
print("         RÉCAPITULATIF SPRINT 1")
print("=" * 55)
print(f"Dataset brut       : {df_raw.shape[0]:,} x {df_raw.shape[1]}")
print(f"Après nettoyage    : {df_clean.shape[0]:,} x {df_clean.shape[1]}")
print(f"Doublons supprimés : {df_raw.shape[0] - df_clean.shape[0]:,}")
print(f"Valeurs manquantes : 0")
print(f"Taux positif       : {df_clean['Diabetes_binary'].mean():.3%}")
print(f"Imbalance ratio    : {imbalance_ratio:.2f}")
print("-" * 55)
print(f"Train : {len(X_train):,}  |  Val : {len(X_val):,}  |  Test : {len(X_test):,}")
print(f"Scaler : StandardScaler (fit sur train uniquement)")
print("=" * 55)

## 17. Analyse RGPD & Éthique

### Cadre légal

Ce projet manipule des **données de santé** au sens de l'art. 9 du RGPD (UE 2016/679). Le traitement est légitimé par l'**art. 9.2.j** qui autorise l'utilisation de telles données à des fins de recherche scientifique d'intérêt public, sous garanties appropriées.

### Anonymisation source

Le dataset BRFSS 2015 a déjà été anonymisé par les CDC avant publication :
- Aucun identifiant direct (pas de nom, adresse, téléphone, date de naissance précise)
- L'âge est regroupé en **13 tranches** — pas l'âge exact
- L'origine ethnique et la zone géographique fine ont été retirées
- Le risque de ré-identification par croisement reste faible étant donné la granularité restreinte

### Inventaire des variables sensibles

| Variable | Sensibilité | Décision |
|---|---|---|
| `HighBP`, `HighChol`, `Stroke`, `HeartDiseaseorAttack` | Santé (art. 9) | ✅ Conservées — facteurs de risque centraux |
| `BMI`, `MentHlth`, `PhysHlth`, `GenHlth` | Santé (art. 9) | ✅ Conservées — indicateurs cliniques |
| `Smoker`, `HvyAlcoholConsump`, `PhysActivity` | Mode de vie | ✅ Conservées — comportements à risque |
| `Sex`, `Age` | Personnel | ✅ Conservées — facteurs cliniques reconnus, non identifiants |
| `Income`, `Education` | Socio-économique | ✅ Conservées **avec vigilance** — audit du biais prévu Sprint 3 |
| Origine ethnique, zone géographique | Non présentes | — Absentes par construction CDC |

### Mesures opérationnelles

- **Minimisation** : aucun croisement de variables ne reconstruit un identifiant indirect
- **Reproductibilité** : `random_state=42` sur tous les splits — décisions traçables
- **Pas de data leakage** : scaler ajusté uniquement sur le train, sauvegardé via joblib
- **Données conservées localement** — aucun envoi vers un service externe

### Points de vigilance pour les sprints suivants

- **Sprint 2** : le déséquilibre des classes (~5.5 : 1) doit être traité — l'accuracy seule masquerait les faux négatifs sur la classe diabète
- **Sprint 3** : audit du biais par sous-groupe (Income, Sex, Age) sur le test set — vérifier que le modèle ne discrimine pas certaines populations
- **Rappel** : ce modèle **n'est pas un dispositif médical** (règlement DM EU 2017/745) et ne peut pas servir de décision automatisée individuelle (art. 22 RGPD)

## 18. Conclusion

## 19. Glossaire